[build]
dockerfilePath = "Dockerfile"

[deploy]
releaseCommand = "npx prisma migrate deploy"
startCommand = "node dist/main"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
